# Dockerfile.streamlit
FROM python:3.10-slim

WORKDIR /app

# Installer les outils de build nécessaires
RUN apt-get update && apt-get install -y build-essential && \
    pip install --upgrade pip setuptools wheel build

# Copier le fichier requirements
COPY requirements.txt ./requirements.txt

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code de l'application
COPY ./Dashboard /app
COPY ./scripts /app/scripts
COPY ./config /app/config

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.enableCORS=false"]